server:
  port: 10000
spring:
  application:
    name: customer
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
---
spring:
  profiles: herokudb
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 2
    url: jdbc:postgresql://ec2-3-230-38-145.compute-1.amazonaws.com/d81rucrl5tc83e
